package com.redhat.bpms.example.pmi;

import java.lang.String;
import java.lang.Double;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements Serializable {

	private static final long serialVersionUID = -6802443485036869625L;

	@org.kie.api.definition.type.Label(value = "SSN")
	private String ssn;
	@org.kie.api.definition.type.Label(value = "name")
	private String name;
	@org.kie.api.definition.type.Label(value = "credit score")
	private Double creditScore;

	public Applicant() {
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(Double creditScore) {
		this.creditScore = creditScore;
	}

	public Applicant(String ssn, String name, Double creditScore) {
		this.ssn = ssn;
		this.name = name;
		this.creditScore = creditScore;
	}

}
