package com.redhat.bpms.example.pmi;

import java.io.Serializable;
import java.lang.Integer;
import java.lang.String;
import java.lang.Double;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("mortgage application")
public class MortgageApplication implements Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private String id;
	@org.kie.api.definition.type.Label("length of loan (years)")
	private Integer lengthOfLoanYears;
	@org.kie.api.definition.type.Label("base loan amount")
	private Integer baseLoanAmount;
	@org.kie.api.definition.type.Label("down payment")
	private Integer downpayment;
	@org.kie.api.definition.type.Label("annual MIP (bps)")
	private Integer annualMIP;
	@org.kie.api.definition.type.Label("program")
	private String program;
	@org.kie.api.definition.type.Label("property")
	private com.redhat.bpms.example.pmi.Property property;
	@org.kie.api.definition.type.Label("LTV")
	private Double ltv;
	@org.kie.api.definition.type.Label("APR")
	private Double apr;
	@org.kie.api.definition.type.Label(value = "applicant")
	private com.redhat.bpms.example.pmi.Applicant applicant;

	public MortgageApplication() {
	}

	public Integer getBaseLoanAmount() {
		return this.baseLoanAmount;
	}

	public void setBaseLoanAmount(Integer baseLoanAmount) {
		this.baseLoanAmount = baseLoanAmount;
	}

	public Integer getAnnualMIP() {
		return this.annualMIP;
	}

	public void setAnnualMIP(Integer annualMIP) {
		this.annualMIP = annualMIP;
	}

	public Integer getLengthOfLoanYears() {
		return this.lengthOfLoanYears;
	}

	public void setLengthOfLoanYears(Integer lengthOfLoanYears) {
		this.lengthOfLoanYears = lengthOfLoanYears;
	}

	public Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(Integer downpayment) {
		this.downpayment = downpayment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProgram() {
		return this.program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	public com.redhat.bpms.example.pmi.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.redhat.bpms.example.pmi.Property property) {
		this.property = property;
	}

	public Double getLtv() {
		return this.ltv;
	}

	public void setLtv(Double ltv) {
		this.ltv = ltv;
	}

	public Double getApr() {
		return this.apr;
	}

	public void setApr(Double apr) {
		this.apr = apr;
	}

	public com.redhat.bpms.example.pmi.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.redhat.bpms.example.pmi.Applicant applicant) {
		this.applicant = applicant;
	}

	public MortgageApplication(String id,
			Integer lengthOfLoanYears,
			Integer baseLoanAmount, Integer downpayment,
			Integer annualMIP, String program,
			com.redhat.bpms.example.pmi.Property property, Double ltv,
			Double apr, com.redhat.bpms.example.pmi.Applicant applicant) {
		this.id = id;
		this.lengthOfLoanYears = lengthOfLoanYears;
		this.baseLoanAmount = baseLoanAmount;
		this.downpayment = downpayment;
		this.annualMIP = annualMIP;
		this.program = program;
		this.property = property;
		this.ltv = ltv;
		this.apr = apr;
		this.applicant = applicant;
	}

}