package com.redhat.bpms.example.pmi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationErrorDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidationErrorDO() {
    }




}